# Generated by Django 4.1.3 on 2022-12-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_generando_tablas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleatencionclinicamodel',
            unique_together={('Atencion', 'Trabajador', 'Areatrab')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleatencionserviciomodel',
            unique_together={('Atencion', 'Trabajador', 'Areatrab')},
        ),
    ]
