# Generated by Django 4.1.3 on 2022-12-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_tercera_migracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariomodel',
            old_name='UsuarioID',
            new_name='id',
        ),
    ]
