# Generated by Django 4.1.3 on 2022-12-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmodel',
            name='MontoT',
            field=models.FloatField(db_column='MontoT', default=0),
        ),
        migrations.AddField(
            model_name='detalleatencionmodel',
            name='MontoD',
            field=models.FloatField(db_column='MontoD', default=0),
        ),
    ]
