# Generated by Django 4.1.3 on 2022-12-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_primera_migracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenmodel',
            name='observacion',
            field=models.TextField(db_column='observacion', null=True),
        ),
    ]
