# Generated by Django 4.1.3 on 2022-12-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cuarta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadormodel',
            name='Usuario',
        ),
    ]
