# Generated by Django 4.1.3 on 2022-12-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_arreglando_relaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleatencionclinicamodel',
            name='Diagnostico',
            field=models.ForeignKey(db_column='DiagnosticoID', default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.diagnosticomodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleatencionserviciomodel',
            name='TipoDetalleAtencion',
            field=models.ForeignKey(db_column='TipodetalleAtencionID', default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipodetalleatencionmodel'),
            preserve_default=False,
        ),
    ]
