# Generated by Django 4.1.3 on 2022-12-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_subiendo_atencions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatoriomodel',
            name='Servicio',
        ),
        migrations.AddField(
            model_name='recordatoriomodel',
            name='TipoDetalleAtencion',
            field=models.ForeignKey(db_column='TipodetalleAtencionID', default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipodetalleatencionmodel'),
            preserve_default=False,
        ),
    ]
