# Generated by Django 4.1.3 on 2022-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_trabajadormodel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientemodel',
            name='Foto',
            field=models.ImageField(blank='', default='', upload_to='fotospet/'),
        ),
    ]
