# Generated by Django 4.1.3 on 2022-12-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_pacientemodel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='Foto',
            field=models.ImageField(blank='', db_column='Foto', default='', upload_to='fotospet/'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='Raza',
            field=models.ForeignKey(db_column='RazaID', on_delete=django.db.models.deletion.CASCADE, to='gestion.razamodel'),
        ),
    ]
