# Generated by Django 4.1.3 on 2022-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_pacientemodel_foto_alter_pacientemodel_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='Foto',
            field=models.ImageField(blank='', db_column='Foto', default='', null=True, upload_to='fotospet/'),
        ),
    ]
